import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans"; // import font
import "./globals.css";
import NavBar from "@/components/nav-bar";
import Footer from "@/components/footer";

import { FaWhatsappSquare } from "react-icons/fa";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.className} antialiased dark:bg-gray-950`}
    >
      <body>
        <div className="fixed text-green-500 top-3/6 right-10 max-sm:top-11/12 max-sm:right-1 z-[999]">
          <Link
            href="https://wa.me/5511956083860?text=Oi%2C%20quero%20conhecer%20a%20academia!"
            target="_blank"
            aria-current="page"
            key="contatos"
          >
            <FaWhatsappSquare size={40} />
          </Link>
        </div>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
